#include "BENSCHILLIBOWL.h"
#include <stdlib.h>
#include <assert.h>
#include <pthread.h>
// Generated by Chat GPT
bool IsEmpty(BENSCHILLIBOWL* bcb) {
    return bcb->current_size == 0;
}

bool IsFull(BENSCHILLIBOWL* bcb) {
    return bcb->current_size == bcb->max_size;
}

/* Pick a random menu item */
MenuItem PickRandomMenuItem() {
    int r = rand() % BENSCHILLIBOWLMenuLength;
    return BENSCHILLIBOWLMenu[r];
}

/* Initialize restaurant */
BENSCHILLIBOWL* OpenRestaurant(int max_size, int expected_num_orders) {
    BENSCHILLIBOWL* bcb = malloc(sizeof(BENSCHILLIBOWL));

    bcb->orders = NULL;
    bcb->current_size = 0;

    bcb->max_size = max_size;
    bcb->expected_num_orders = expected_num_orders;
    bcb->orders_handled = 0;
    bcb->next_order_number = 1;

    pthread_mutex_init(&bcb->mutex, NULL);
    pthread_cond_init(&bcb->can_add_orders, NULL);
    pthread_cond_init(&bcb->can_get_orders, NULL);

    return bcb;
}

/* Add order to queue */
int AddOrder(BENSCHILLIBOWL* bcb, Order* order) {
    pthread_mutex_lock(&bcb->mutex);

    while (IsFull(bcb)) {
        pthread_cond_wait(&bcb->can_add_orders, &bcb->mutex);
    }

    order->order_number = bcb->next_order_number++;
    order->next = NULL;

    if (bcb->orders == NULL) {
        bcb->orders = order;
    } else {
        Order* tail = bcb->orders;
        while (tail->next != NULL) tail = tail->next;
        tail->next = order;
    }

    bcb->current_size++;

    pthread_cond_signal(&bcb->can_get_orders);
    pthread_mutex_unlock(&bcb->mutex);

    return order->order_number;
}

/* Get order from queue */
Order* GetOrder(BENSCHILLIBOWL* bcb) {
    pthread_mutex_lock(&bcb->mutex);

    while (IsEmpty(bcb) &&
           bcb->orders_handled < bcb->expected_num_orders) {
        pthread_cond_wait(&bcb->can_get_orders, &bcb->mutex);
    }

    if (IsEmpty(bcb) &&
        bcb->orders_handled == bcb->expected_num_orders) {
        pthread_mutex_unlock(&bcb->mutex);
        return NULL;
    }

    Order* o = bcb->orders;
    bcb->orders = o->next;
    bcb->current_size--;
    bcb->orders_handled++;

    pthread_cond_signal(&bcb->can_add_orders);
    pthread_mutex_unlock(&bcb->mutex);

    return o;
}

/* Properly close restaurant & free ALL resources */
void CloseRestaurant(BENSCHILLIBOWL* bcb) {
    pthread_mutex_lock(&bcb->mutex);

    assert(bcb->orders_handled == bcb->expected_num_orders);

    pthread_mutex_unlock(&bcb->mutex);

    pthread_mutex_destroy(&bcb->mutex);
    pthread_cond_destroy(&bcb->can_add_orders);
    pthread_cond_destroy(&bcb->can_get_orders);

    Order* o = bcb->orders;
    while (o != NULL) {
        Order* tmp = o;
        o = o->next;
        free(tmp);
    }

    free(bcb);

    printf("Restaurant closed successfully.\n");
}
