#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "list.h"
// Generated by Chat GPT
list_t *list_alloc() {
    list_t *l = malloc(sizeof(list_t));
    l->head = NULL;
    return l;
}

void list_free(list_t *l) {
    node_t *cur = l->head;
    node_t *tmp;
    while (cur != NULL) {
        tmp = cur->next;
        free(cur);
        cur = tmp;
    }
    free(l);
}

void list_add_to_front(list_t *l, int value) {
    node_t *n = malloc(sizeof(node_t));
    n->value = value;
    n->next = l->head;
    l->head = n;
}

void list_add_to_back(list_t *l, int value) {
    node_t *n = malloc(sizeof(node_t));
    n->value = value;
    n->next = NULL;

    if (l->head == NULL) {
        l->head = n;
        return;
    }
    node_t *cur = l->head;
    while (cur->next != NULL) {
        cur = cur->next;
    }
    cur->next = n;
}

void list_add_at_index(list_t *l, int index, int value) {
    if (index == 0) {
        list_add_to_front(l, value);
        return;
    }

    node_t *cur = l->head;
    for (int i = 0; i < index - 1 && cur != NULL; i++) {
        cur = cur->next;
    }
    if (cur == NULL)
        return;

    node_t *n = malloc(sizeof(node_t));
    n->value = value;
    n->next = cur->next;
    cur->next = n;
}

int list_remove_from_front(list_t *l) {
    if (l->head == NULL) return -1;

    node_t *tmp = l->head;
    int val = tmp->value;
    l->head = tmp->next;
    free(tmp);
    return val;
}

int list_remove_from_back(list_t *l) {
    if (l->head == NULL) return -1;

    if (l->head->next == NULL) {
        int val = l->head->value;
        free(l->head);
        l->head = NULL;
        return val;
    }

    node_t *cur = l->head;
    while (cur->next->next != NULL) {
        cur = cur->next;
    }

    int val = cur->next->value;
    free(cur->next);
    cur->next = NULL;

    return val;
}

int list_remove_at_index(list_t *l, int index) {
    if (index == 0) {
        return list_remove_from_front(l);
    }

    node_t *cur = l->head;
    for (int i = 0; i < index - 1 && cur != NULL; i++) {
        cur = cur->next;
    }

    if (cur == NULL || cur->next == NULL) return -1;

    node_t *tmp = cur->next;
    int val = tmp->value;
    cur->next = tmp->next;
    free(tmp);

    return val;
}

int list_get_elem_at(list_t *l, int index) {
    node_t *cur = l->head;
    for (int i = 0; i < index && cur != NULL; i++) {
        cur = cur->next;
    }
    return (cur == NULL) ? -1 : cur->value;
}

int list_length(list_t *l) {
    int count = 0;
    node_t *cur = l->head;
    while (cur != NULL) {
        count++;
        cur = cur->next;
    }
    return count;
}

char *listToString(list_t *l) {
    static char buffer[512];
    buffer[0] = '\0';

    node_t *cur = l->head;
    while (cur != NULL) {
        char temp[32];
        sprintf(temp, "%d ", cur->value);
        strcat(buffer, temp);
        cur = cur->next;
    }
    return buffer;
}
