#ifndef LIST_H
#define LIST_H
// Generated by Chat GPT
// Linked List structure definitions

typedef struct node {
    int value;
    struct node *next;
} node_t;

typedef struct list {
    node_t *head;
} list_t;

// Function prototypes corresponding to Lab #1

// Allocate/Free
list_t *list_alloc();
void list_free(list_t *l);

// Add operations
void list_add_to_front(list_t *l, int value);
void list_add_to_back(list_t *l, int value);
void list_add_at_index(list_t *l, int index, int value);

// Remove operations
int list_remove_from_front(list_t *l);
int list_remove_from_back(list_t *l);
int list_remove_at_index(list_t *l, int index);

// Lookup operations
int list_get_elem_at(list_t *l, int index);
int list_length(list_t *l);

// String conversion
char *listToString(list_t *l);

#endif
