#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <pthread.h>

#include "BENSCHILLIBOWL.h"
//Generated by Chat GPT
#define BENSCHILLIBOWL_SIZE 100
#define NUM_CUSTOMERS 90
#define NUM_COOKS 10
#define ORDERS_PER_CUSTOMER 3
#define EXPECTED_NUM_ORDERS (NUM_CUSTOMERS * ORDERS_PER_CUSTOMER)

BENSCHILLIBOWL *bcb;

/*
 * Customer thread:
 *  - makes ORDERS_PER_CUSTOMER orders
 *  - each allocated, filled, and added to restaurant
 */
void* BENSCHILLIBOWLCustomer(void* arg) {
    int customer_id = (int)(long) arg;

    for (int i = 0; i < ORDERS_PER_CUSTOMER; i++) {
        Order* o = malloc(sizeof(Order));
        o->menu_item = PickRandomMenuItem();
        o->customer_id = customer_id;
        o->next = NULL;

        AddOrder(bcb, o);
    }

    pthread_exit(NULL);
}

/*
 * Cook thread:
 *  - keeps getting orders until restaurant returns NULL
 *  - frees orders when fulfilled
 */
void* BENSCHILLIBOWLCook(void* arg) {
    int cook_id = (int)(long) arg;
    int fulfilled = 0;

    while (1) {
        Order* o = GetOrder(bcb);
        if (o == NULL) break;

        fulfilled++;
        printf("Cook %d fulfilled order %d for customer %d (%s)\n",
               cook_id, o->order_number, o->customer_id, o->menu_item);

        free(o);
    }

    printf("Cook %d fulfilled %d orders\n", cook_id, fulfilled);
    pthread_exit(NULL);
}

/*
 * main:
 *  - opens restaurant
 *  - creates all threads
 *  - waits for all to finish
 *  - closes restaurant (frees memory + destroys sync objects)
 */
int main() {
    srand(time(NULL));

    bcb = OpenRestaurant(BENSCHILLIBOWL_SIZE, EXPECTED_NUM_ORDERS);

    pthread_t customers[NUM_CUSTOMERS];
    pthread_t cooks[NUM_COOKS];

    for (int i = 0; i < NUM_CUSTOMERS; i++) {
        pthread_create(&customers[i], NULL,
                       BENSCHILLIBOWLCustomer, (void*)(long)i);
    }

    for (int i = 0; i < NUM_COOKS; i++) {
        pthread_create(&cooks[i], NULL,
                       BENSCHILLIBOWLCook, (void*)(long)i);
    }

    for (int i = 0; i < NUM_CUSTOMERS; i++)
        pthread_join(customers[i], NULL);

    for (int i = 0; i < NUM_COOKS; i++)
        pthread_join(cooks[i], NULL);

    CloseRestaurant(bcb);

    return 0;
}
