// C program for implementation of Simulation 
#include<stdio.h> 
#include<limits.h>
#include<stdlib.h>
#include <string.h>
#include "process.h"
#include "util.h"
// Code generated by DeepSeek AI

// Function to find the waiting time for all processes using Round Robin
void findWaitingTimeRR(ProcessType plist[], int n, int quantum) 
{ 
    // Allocate memory for remaining burst times and completion flags
    int *rem_bt = (int *)malloc(n * sizeof(int));
    int *is_completed = (int *)malloc(n * sizeof(int));
    
    if (!rem_bt || !is_completed) {
        fprintf(stderr, "Memory allocation failed\n");
        exit(1);
    }
    
    // Initialize arrays
    for (int i = 0; i < n; i++) {
        rem_bt[i] = plist[i].bt;
        is_completed[i] = 0;
        plist[i].wt = 0;
        plist[i].tat = 0;
    }
    
    int t = 0; // Current time
    int completed = 0;
    int *arrived = (int *)malloc(n * sizeof(int));
    
    if (!arrived) {
        fprintf(stderr, "Memory allocation failed\n");
        exit(1);
    }
    
    // Continue until all processes are completed
    while (completed < n) {
        // Check which processes have arrived
        for (int i = 0; i < n; i++) {
            arrived[i] = (plist[i].art <= t && !is_completed[i]) ? 1 : 0;
        }
        
        int all_idle = 1;
        
        // Execute processes in round-robin order
        for (int i = 0; i < n; i++) {
            if (arrived[i] && rem_bt[i] > 0) {
                all_idle = 0;
                
                if (rem_bt[i] > quantum) {
                    // Process executes for full quantum
                    t += quantum;
                    rem_bt[i] -= quantum;
                    
                    // Update waiting time for other waiting processes
                    for (int j = 0; j < n; j++) {
                        if (j != i && plist[j].art <= t && !is_completed[j] && rem_bt[j] > 0) {
                            plist[j].wt += quantum;
                        }
                    }
                } else {
                    // Last cycle for this process
                    int exec_time = rem_bt[i];
                    t += exec_time;
                    rem_bt[i] = 0;
                    is_completed[i] = 1;
                    completed++;
                    
                    // Calculate waiting time
                    plist[i].wt = t - plist[i].bt - plist[i].art;
                    if (plist[i].wt < 0) plist[i].wt = 0;
                    
                    // Update waiting time for other waiting processes
                    for (int j = 0; j < n; j++) {
                        if (j != i && plist[j].art <= t && !is_completed[j] && rem_bt[j] > 0) {
                            plist[j].wt += exec_time;
                        }
                    }
                }
                
                // Break and restart the loop to handle new arrivals
                break;
            }
        }
        
        if (all_idle) {
            // No process is ready, advance to next arrival time
            int next_arrival = INT_MAX;
            for (int i = 0; i < n; i++) {
                if (!is_completed[i] && plist[i].art > t && plist[i].art < next_arrival) {
                    next_arrival = plist[i].art;
                }
            }
            if (next_arrival != INT_MAX) {
                t = next_arrival;
            } else {
                t++;
            }
        }
    }
    
    free(rem_bt);
    free(is_completed);
    free(arrived);
} 

// Function to find the waiting time for all processes using SJF (non-preemptive)
void findWaitingTimeSJF(ProcessType plist[], int n)
{ 
    // Allocate memory for completion flags
    int *is_completed = (int *)calloc(n, sizeof(int));
    int *original_order = (int *)malloc(n * sizeof(int));
    
    if (!is_completed || !original_order) {
        fprintf(stderr, "Memory allocation failed\n");
        exit(1);
    }
    
    // Store original order for output
    for (int i = 0; i < n; i++) {
        original_order[i] = i;
        plist[i].wt = 0;
        plist[i].tat = 0;
    }
    
    // Sort processes by arrival time (and then by burst time for same arrival)
    for (int i = 0; i < n - 1; i++) {
        for (int j = 0; j < n - i - 1; j++) {
            if (plist[j].art > plist[j + 1].art || 
                (plist[j].art == plist[j + 1].art && plist[j].bt > plist[j + 1].bt)) {
                ProcessType temp = plist[j];
                plist[j] = plist[j + 1];
                plist[j + 1] = temp;
                
                int temp_idx = original_order[j];
                original_order[j] = original_order[j + 1];
                original_order[j + 1] = temp_idx;
            }
        }
    }
    
    int current_time = 0;
    int completed = 0;
    
    while (completed < n) {
        int idx = -1;
        int min_bt = INT_MAX;
        
        // Find the process with minimum burst time among arrived processes
        for (int i = 0; i < n; i++) {
            if (!is_completed[i] && plist[i].art <= current_time && plist[i].bt < min_bt) {
                min_bt = plist[i].bt;
                idx = i;
            }
        }
        
        if (idx != -1) {
            // Execute the selected process to completion (non-preemptive)
            plist[idx].wt = current_time - plist[idx].art;
            if (plist[idx].wt < 0) plist[idx].wt = 0;
            
            current_time += plist[idx].bt;
            is_completed[idx] = 1;
            completed++;
        } else {
            // No process has arrived, advance to next arrival time
            int next_arrival = INT_MAX;
            for (int i = 0; i < n; i++) {
                if (!is_completed[i] && plist[i].art < next_arrival) {
                    next_arrival = plist[i].art;
                }
            }
            current_time = next_arrival;
        }
    }
    
    // Restore original order
    ProcessType *temp_plist = (ProcessType *)malloc(n * sizeof(ProcessType));
    if (!temp_plist) {
        fprintf(stderr, "Memory allocation failed\n");
        exit(1);
    }
    
    memcpy(temp_plist, plist, n * sizeof(ProcessType));
    for (int i = 0; i < n; i++) {
        plist[original_order[i]] = temp_plist[i];
    }
    
    free(is_completed);
    free(original_order);
    free(temp_plist);
} 

// Function to find the waiting time for all processes using FCFS
void findWaitingTimeFCFS(ProcessType plist[], int n)
{ 
    // Sort processes by arrival time
    for (int i = 0; i < n - 1; i++) {
        for (int j = 0; j < n - i - 1; j++) {
            if (plist[j].art > plist[j + 1].art) {
                ProcessType temp = plist[j];
                plist[j] = plist[j + 1];
                plist[j + 1] = temp;
            }
        }
    }
    
    // Calculate waiting times
    int *completion_time = (int *)malloc(n * sizeof(int));
    if (!completion_time) {
        fprintf(stderr, "Memory allocation failed\n");
        exit(1);
    }
    
    // First process
    if (plist[0].art > 0) {
        completion_time[0] = plist[0].art + plist[0].bt;
    } else {
        completion_time[0] = plist[0].bt;
    }
    plist[0].wt = 0;
    
    // Subsequent processes
    for (int i = 1; i < n; i++) {
        if (completion_time[i - 1] < plist[i].art) {
            completion_time[i] = plist[i].art + plist[i].bt;
            plist[i].wt = 0;
        } else {
            completion_time[i] = completion_time[i - 1] + plist[i].bt;
            plist[i].wt = completion_time[i - 1] - plist[i].art;
            if (plist[i].wt < 0) plist[i].wt = 0;
        }
    }
    
    free(completion_time);
} 
  
// Function to calculate turn around time 
void findTurnAroundTime( ProcessType plist[], int n)
{ 
    // calculating turnaround time by adding bt[i] + wt[i] 
    for (int i = 0; i < n; i++) {
        plist[i].tat = plist[i].bt + plist[i].wt;
    }
} 
  
// Function to sort the Process acc. to priority (higher number = higher priority)
int priority_comparer(const void *a, const void *b)
{ 
    ProcessType *p1 = (ProcessType *)a;
    ProcessType *p2 = (ProcessType *)b;
    
    // Higher priority number means higher priority (larger number = higher priority)
    if (p1->pri > p2->pri) {
        return -1; // p1 has higher priority
    } else if (p1->pri < p2->pri) {
        return 1;  // p2 has higher priority
    } else {
        // If priorities are equal, sort by arrival time (earlier first)
        if (p1->art < p2->art) {
            return -1;
        } else if (p1->art > p2->art) {
            return 1;
        } else {
            return 0;
        }
    }
}

// Function to sort by arrival time for FCFS
int arrival_comparer(const void *a, const void *b)
{
    ProcessType *p1 = (ProcessType *)a;
    ProcessType *p2 = (ProcessType *)b;
    
    if (p1->art < p2->art) {
        return -1;
    } else if (p1->art > p2->art) {
        return 1;
    } else {
        return 0;
    }
}

//Function to calculate average time for FCFS
void findavgTimeFCFS( ProcessType plist[], int n) 
{ 
    // Function to find waiting time of all processes 
    findWaitingTimeFCFS(plist, n); 
  
    // Function to find turn around time for all processes 
    findTurnAroundTime(plist, n); 
  
    // Display processes along with all details 
    printf("\n*********\nFCFS (First Come First Serve)\n");
    printf("Note: Processes are sorted by arrival time\n");
}

//Function to calculate average time for SJF
void findavgTimeSJF( ProcessType plist[], int n) 
{ 
    // Function to find waiting time of all processes 
    findWaitingTimeSJF(plist, n); 
  
    // Function to find turn around time for all processes 
    findTurnAroundTime(plist, n); 
  
    // Display processes along with all details 
    printf("\n*********\nSJF (Shortest Job First - Non-Preemptive)\n");
    printf("Note: Among arrived processes, shortest burst time executes first\n");
}

//Function to calculate average time for RR
void findavgTimeRR( ProcessType plist[], int n, int quantum) 
{ 
    // Function to find waiting time of all processes 
    findWaitingTimeRR(plist, n, quantum); 
  
    // Function to find turn around time for all processes 
    findTurnAroundTime(plist, n); 
  
    // Display processes along with all details 
    printf("\n*********\nRR (Round Robin) Quantum = %d\n", quantum);
    printf("Note: Processes execute in cycles, each up to quantum time units\n");
}

//Function to calculate average time for Priority
void findavgTimePriority( ProcessType plist[], int n) 
{ 
    // Make a copy of the process list
    ProcessType *plist_copy = (ProcessType *)malloc(n * sizeof(ProcessType));
    if (!plist_copy) {
        fprintf(stderr, "Memory allocation failed\n");
        exit(1);
    }
    memcpy(plist_copy, plist, n * sizeof(ProcessType));
    
    // Sort by arrival time first
    qsort(plist_copy, n, sizeof(ProcessType), arrival_comparer);
    
    int *is_completed = (int *)calloc(n, sizeof(int));
    int *original_order = (int *)malloc(n * sizeof(int));
    
    if (!is_completed || !original_order) {
        fprintf(stderr, "Memory allocation failed\n");
        exit(1);
    }
    
    for (int i = 0; i < n; i++) {
        original_order[i] = i;
        plist_copy[i].wt = 0;
        plist_copy[i].tat = 0;
    }
    
    int current_time = 0;
    int completed = 0;
    
    while (completed < n) {
        int idx = -1;
        int highest_priority = -1;
        
        // Find process with highest priority among arrived processes
        for (int i = 0; i < n; i++) {
            if (!is_completed[i] && plist_copy[i].art <= current_time) {
                if (idx == -1 || plist_copy[i].pri > highest_priority) {
                    highest_priority = plist_copy[i].pri;
                    idx = i;
                }
            }
        }
        
        if (idx != -1) {
            // Execute the selected process to completion (non-preemptive)
            plist_copy[idx].wt = current_time - plist_copy[idx].art;
            if (plist_copy[idx].wt < 0) plist_copy[idx].wt = 0;
            
            current_time += plist_copy[idx].bt;
            is_completed[idx] = 1;
            completed++;
        } else {
            // No process has arrived, advance to next arrival time
            int next_arrival = INT_MAX;
            for (int i = 0; i < n; i++) {
                if (!is_completed[i] && plist_copy[i].art < next_arrival) {
                    next_arrival = plist_copy[i].art;
                }
            }
            current_time = next_arrival;
        }
    }
    
    // Calculate turnaround times
    for (int i = 0; i < n; i++) {
        plist_copy[i].tat = plist_copy[i].bt + plist_copy[i].wt;
    }
    
    // Copy results back to original array (maintaining original order)
    for (int i = 0; i < n; i++) {
        plist[original_order[i]].wt = plist_copy[i].wt;
        plist[original_order[i]].tat = plist_copy[i].tat;
    }
    
    free(plist_copy);
    free(is_completed);
    free(original_order);
  
    // Display processes along with all details 
    printf("\n*********\nPriority Scheduling (Non-Preemptive)\n");
    printf("Note: Higher priority number = higher priority\n");
}

void printMetrics(ProcessType plist[], int n)
{
    int total_wt = 0, total_tat = 0; 
    float awt, att;
    
    printf("\tProcess\tBurst Time\tArrival Time\tPriority\tWaiting Time\tTurnaround Time\n"); 
    printf("\t-------\t----------\t------------\t--------\t------------\t---------------\n");
  
    // Calculate total waiting time and total turn around time 
    for (int i = 0; i < n; i++) 
    { 
        total_wt = total_wt + plist[i].wt; 
        total_tat = total_tat + plist[i].tat; 
        printf("\t%d\t%d\t\t%d\t\t%d\t\t%d\t\t%d\n", 
               plist[i].pid, plist[i].bt, plist[i].art, plist[i].pri, plist[i].wt, plist[i].tat); 
    } 
  
    awt = ((float)total_wt / (float)n);
    att = ((float)total_tat / (float)n);
    
    printf("\nAverage waiting time = %.2f", awt); 
    printf("\nAverage turnaround time = %.2f\n", att); 
} 

ProcessType * initProc(char *filename, int *n) 
{
  	FILE *input_file = fopen(filename, "r");
	  if (!input_file) {
		    fprintf(stderr, "Error: Cannot open file '%s'\n", filename);
		    fflush(stdout);
		    exit(1);
	  }

    ProcessType *plist = parse_file(input_file, n);
    
    // Validate input data
    for (int i = 0; i < *n; i++) {
        if (plist[i].bt <= 0) {
            fprintf(stderr, "Error: Process %d has invalid burst time %d\n", 
                    plist[i].pid, plist[i].bt);
            exit(1);
        }
        if (plist[i].art < 0) {
            fprintf(stderr, "Error: Process %d has negative arrival time %d\n", 
                    plist[i].pid, plist[i].art);
            exit(1);
        }
    }
  
    fclose(input_file);
  
    return plist;
}

// Function to free process list memory
void freeProcList(ProcessType *plist) {
    if (plist != NULL) {
        free(plist);
    }
}
  
// Driver code 
int main(int argc, char *argv[]) 
{ 
    int n; 
    int quantum = 2;
    ProcessType *proc_list;
  
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <input-file-path>\n", argv[0]);
        fflush(stdout);
        return 1;
    }
    
    // FCFS
    printf("\n===========================================");
    n = 0;
    proc_list = initProc(argv[1], &n);
    findavgTimeFCFS(proc_list, n);
    printMetrics(proc_list, n);
    freeProcList(proc_list);
  
    // SJF
    printf("\n===========================================");
    n = 0;
    proc_list = initProc(argv[1], &n);
    findavgTimeSJF(proc_list, n); 
    printMetrics(proc_list, n);
    freeProcList(proc_list);
  
    // Priority
    printf("\n===========================================");
    n = 0; 
    proc_list = initProc(argv[1], &n);
    findavgTimePriority(proc_list, n); 
    printMetrics(proc_list, n);
    freeProcList(proc_list);
    
    // RR
    printf("\n===========================================");
    n = 0;
    proc_list = initProc(argv[1], &n);
    findavgTimeRR(proc_list, n, quantum); 
    printMetrics(proc_list, n);
    freeProcList(proc_list);
    
    printf("\n===========================================\n");
    printf("Scheduling Simulation Complete\n");
    
    return 0; 
}