#include <stdio.h>
#include <stdlib.h>
// Generated by Chat GPT AI

/* IMPLEMENT ME: Declare your functions here */
int add(int a, int b);
int subtract(int a, int b);
int multiply(int a, int b);
int divide(int a, int b);
int exit_program(int a, int b);

int main(void)
{
    int a = 6;
    int b = 3;
    char choice;

    printf("Operand ‘a’ : %d | Operand ‘b’ : %d\n", a, b);
    printf("Specify the operation to perform (0 : add | 1 : subtract | 2 : Multiply | 3 : divide | 4 : exit): ");

    scanf(" %c", &choice);

    // Array of function pointers
    int (*ops[5])(int, int) = { add, subtract, multiply, divide, exit_program };

    // Convert character '0'...'4' → index 0...4
    int index = choice - '0';

    // Call the function via pointer (no conditionals!)
    int result = ops[index](a, b);

    printf("x = %d\n", result);

    return 0;
}

/* IMPLEMENT ME: Define your functions here */
int add(int a, int b) {
    printf("Adding ‘a’ and ‘b’\n");
    return a + b;
}

int subtract(int a, int b) {
    printf("Subtracting ‘b’ from ‘a’\n");
    return a - b;
}

int multiply(int a, int b) {
    printf("Multiplying ‘a’ and ‘b’\n");
    return a * b;
}

int divide(int a, int b) {
    printf("Dividing ‘a’ by ‘b’\n");
    return a / b;
}

int exit_program(int a, int b) {
    exit(0);
}
